// Generated by ReScript, PLEASE EDIT WITH CARE

let Dynamic = {};

let $$Error = {};

let Head = {};

// biome-ignore lint/style/useConst: <explanation>
let Image = {};

let Link = {};

let Router = {};

let Res = {};

let GetServerSideProps = {
  Res: Res,
};

let GetStaticPaths = {};

let GetStaticProps = {};

let Page = {
  GetServerSideProps: GetServerSideProps,
  GetStaticPaths: GetStaticPaths,
  GetStaticProps: GetStaticProps,
};

let Script = {};

export { Dynamic, $$Error, Head, Image, Link, Router, Page, Script };
/* No side effect */
