// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function $$default(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                props.msg,
                JsxRuntime.jsx("a", {
                      children: "`src/Examples.res`",
                      href: props.href,
                      target: "_blank"
                    })
              ]
            });
}

function getServerSideProps(_ctx) {
  return Promise.resolve({
              props: {
                msg: "This page was rendered with getServerSideProps. You can find the source code here: ",
                href: "https://github.com/ryyppy/nextjs-default/tree/master/src/Examples.res"
              }
            });
}

export {
  $$default as default,
  getServerSideProps ,
}
/* react/jsx-runtime Not a pure module */
